name: mysheets
description: "A powerful spreadsheet application built with Flutter"

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  # Supabase - for backend and realtime support
  supabase_flutter: ^2.5.0
  
  # State Management
  provider: ^6.1.1
  
  # File Handling
  file_picker: ^6.1.1
  csv: ^5.1.1
  path_provider: ^2.1.1
  excel: ^4.0.6  # For Excel import/export
  
  # Local Storage
  shared_preferences: ^2.5.3  # For storing theme and settings
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true